<?php

/**
 * @file
 * Contains emoji_reactions_snackbars.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function emoji_reactions_snackbars_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the emoji_reactions_snackbars module.
    case 'help.page.emoji_reactions_snackbars':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Snackbars') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function emoji_reactions_snackbars_theme() {
  return [
    'emoji_reactions_snackbar_container' => [
      'render element' => 'children',
    ],
    'emoji_reactions_snackbar' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function emoji_reactions_snackbars_preprocess_page(&$variables) {
  if (\Drupal::service('router.admin_context')->isAdminRoute()) {
    return;
  }
  $variables['#attached']['library'][] = 'emoji_reactions_snackbars/snackbars';
}
